const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {execFile,spawn}=require('child_process');
const PROFILES={phone:{width:1080,height:1920,density:420},tablet:{width:1600,height:2560,density:320},tv:{width:1920,height:1080,density:240}};
function emulatorStartArgs(p,port){return ['-avd',p.name,'-port',String(port),'-no-snapshot-load','-no-snapshot-save',...(p.graphics==='auto'?['-gpu','auto']:['-gpu','swiftshader','-feature','-Vulkan']),...(p.headless===true?['-no-window','-no-boot-anim']:[])];}
function cleanEmulatorLog(text){return String(text).replace(/\x1b\[[0-9;]*m/g,'');}
function run(file,args,timeout=30000,binary=false){return new Promise((resolve,reject)=>execFile(file,args,{shell:false,windowsHide:true,timeout,maxBuffer:16*1024*1024,encoding:binary?null:'utf8'},(error,stdout,stderr)=>{if(error)reject(new Error(String(stderr||stdout||error.message).slice(0,8000)));else resolve(stdout)}));}
function diagnose(message){const m=String(message);if(/multiple emulators with the same AVD/i.test(m))return 'Cet appareil Android est déjà utilisé par un autre émulateur. Android refuse une deuxième instance. Revenez à Simulation locale ou fermez l’autre fenêtre Android avant de réessayer.';if(/NO_MATCHING_ABIS/i.test(m))return 'Architecture incompatible : choisir une image système correspondant aux bibliothèques natives de cet APK. '+m;if(/OLDER_SDK/i.test(m))return 'API Android trop ancienne pour cet APK. '+m;if(/UPDATE_INCOMPATIBLE/i.test(m))return 'Signature différente de la version installée. Les données existantes sont conservées ; utiliser un autre appareil virtuel. '+m;if(/MISSING_SPLIT/i.test(m))return 'APK incomplet : cette application exige plusieurs APK fractionnés. Sélectionner un APK autonome complet ; les archives APKS/XAPK ne sont pas installées par ce parcours. '+m;if(/MISSING_SHARED_LIBRARY/i.test(m))return 'Bibliothèque système requise absente (services Google ou matériel spécifique possibles). '+m;return m;}
function register({app,ipcMain,dialog,mainWindow,studioWindow=()=>null,resolveApk=()=>{throw Error('Source APK indisponible.')}}){
 let sdk='',selected=null,serial='',packageName='',busy=false,mutationBusy=false,pendingStart=null;const mutations=new Set(['sdk','pick','create','start','connect','install','launch','stop','video-start','launch-installed']);const launched=new Set();
 const settingsFile=()=>path.join(app.getPath('userData'),'android-lab.json');
 try{sdk=JSON.parse(fs.readFileSync(settingsFile(),'utf8')).sdk||''}catch{}
 const avdHome=()=>process.env.ANDROID_AVD_HOME||path.join(app.getPath('userData'),'android-avds');
 const persist=()=>{fs.mkdirSync(path.dirname(settingsFile()),{recursive:true});fs.writeFileSync(settingsFile(),JSON.stringify({sdk},null,2))};
 const tool=name=>{const p=path.join(sdk,name);if(!fs.existsSync(p))throw new Error('Outil absent : '+p);return p};
 const adb=args=>run(tool('platform-tools/adb.exe'),args);
 let videoOwner=null,preparedPlan=null;
 const trusted=event=>[mainWindow(),studioWindow()].some(w=>w&&event.sender===w.webContents)&&event.senderFrame===event.sender.mainFrame;
 const notify=(owner,p)=>{if(owner&&!owner.isDestroyed())owner.send('android:progress',p)};
 const video=new (require('./android-video.cjs').AndroidVideo)({adb,adbPath:()=>tool('platform-tools/adb.exe'),window:()=>{const windows=[mainWindow(),studioWindow()];return windows.find(w=>w&&w.webContents===videoOwner)||mainWindow()}});
 app.on?.('before-quit',()=>video.stop());
 app.on?.('before-quit',()=>{for(const id of launched){try{spawn(tool('platform-tools/adb.exe'),['-s',id,'emu','kill'],{shell:false,windowsHide:true,stdio:'ignore'}).unref();}catch{}}});
 ipcMain.on?.('android:video-ack',(event,p)=>{if(trusted(event)&&event.sender===videoOwner&&p&&Number.isInteger(p.id)&&Number.isInteger(p.sequence))video.ack(p.id,p.sequence)});
 const device=async()=>{if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(serial))throw new Error('Sélectionner un appareil Android connecté et autorisé.');const list=await adb(['devices']);if(!list.split(/\r?\n/).some(l=>l.trim()===serial+'\tdevice'))throw new Error('Appareil hors ligne ou non autorisé.');return serial};
 const operations=new Map();
 const on=(name,fn)=>{operations.set(name,fn);ipcMain.handle('android:'+name,async(event,p={})=>{if(!trusted(event))return {ok:false,error:'Origine IPC refusée'};if(!p||typeof p!=='object'||Array.isArray(p))return {ok:false,error:'Paramètres invalides'};if(mutations.has(name)&&mutationBusy)return {ok:false,error:'Une opération Android est déjà en cours. Attendre sa fin.'};if(mutations.has(name))mutationBusy=true;try{if(['video-start','run-source'].includes(name))videoOwner=event.sender;return {ok:true,...await fn(p,event)}}catch(e){return {ok:false,error:diagnose(e.message)}}finally{if(mutations.has(name))mutationBusy=false}});};
 const avds=()=>{const dir=avdHome();if(!fs.existsSync(dir))return [];return fs.readdirSync(dir).filter(n=>n.endsWith('.ini')).map(n=>{const text=fs.readFileSync(path.join(dir,n),'utf8');const folder=(text.match(/^path=(.+)$/m)||[])[1]?.trim();let config='';try{config=fs.readFileSync(path.join(folder,'config.ini'),'utf8')}catch{}return {name:n.slice(0,-4),profile:/tv|television/i.test(config)?'tv':/tablet/i.test(config)?'tablet':'phone'};});};
 const images=()=>{const out=[],base=path.join(sdk,'system-images');if(!fs.existsSync(base))return out;for(const api of fs.readdirSync(base))for(const tag of fs.readdirSync(path.join(base,api)))for(const abi of fs.readdirSync(path.join(base,api,tag)))if(fs.existsSync(path.join(base,api,tag,abi,'system.img')))out.push({id:[api,tag,abi].join('/'),api,tag,abi});return out;};
 function detectSdk(){if(sdk&&!fs.existsSync(path.join(sdk,'platform-tools','adb.exe')))sdk='';if(!sdk||!fs.existsSync(path.join(sdk,'emulator','emulator.exe'))){const bundled=app.isPackaged?path.join(process.resourcesPath,'apk-runtime','sdk'):path.join(__dirname,'runtime','sdk');const candidates=[sdk,process.env.ANDROID_SDK_ROOT,process.env.ANDROID_HOME,path.join(app.getPath('userData'),'android-sdk'),path.join(process.env.LOCALAPPDATA||'', 'Android','Sdk'),bundled];const adbPath=(process.env.PATH||'').split(path.delimiter).find(p=>fs.existsSync(path.join(p,'adb.exe')));if(adbPath)candidates.push(path.dirname(adbPath));sdk=candidates.find(p=>p&&fs.existsSync(path.join(p,'emulator','emulator.exe'))&&fs.existsSync(path.join(p,'platform-tools','adb.exe')))||candidates.find(p=>p&&fs.existsSync(path.join(p,'platform-tools','adb.exe')))||'';if(sdk)persist();}
}
 on('status',async()=>{detectSdk();
 let devices=[];if(sdk&&fs.existsSync(path.join(sdk,'platform-tools','adb.exe')))devices=(await adb(['devices'])).split(/\r?\n/).filter(l=>/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}\s+device$/.test(l)).map(l=>l.split(/\s/)[0]);let acceleration='Émulateur absent';if(fs.existsSync(path.join(sdk,'emulator','emulator.exe')))try{acceleration=await run(tool('emulator/emulator.exe'),['-accel-check'])}catch(e){acceleration=e.message}let environment=null;if(devices.includes(serial)){const [api,abis,google]=await Promise.all([adb(['-s',serial,'shell','getprop','ro.build.version.sdk']),adb(['-s',serial,'shell','getprop','ro.product.cpu.abilist']),adb(['-s',serial,'shell','pm','path','com.google.android.gms']).catch(()=>'')]);environment={api:api.trim(),abis:abis.trim(),googleServices:/package:/.test(google)}}return {environment,sdk,adb:fs.existsSync(path.join(sdk,'platform-tools','adb.exe')),emulator:fs.existsSync(path.join(sdk,'emulator','emulator.exe')),avds:avds(),images:images(),devices,serial,acceleration};});
 on('sdk',async()=>{await video.stop();const r=await dialog.showOpenDialog({title:'Choisir le dossier Android SDK',properties:['openDirectory']});if(r.canceled)return {canceled:true};const root=fs.realpathSync(r.filePaths[0]);if(!fs.existsSync(path.join(root,'platform-tools','adb.exe')))throw new Error('Ce dossier ne contient pas platform-tools/adb.exe.');sdk=root;persist();return {sdk};});
 function aapt(){
 const bundled=app.isPackaged?path.join(process.resourcesPath,'apk-runtime','sdk'):path.join(__dirname,'runtime','sdk');
 for(const root of [...new Set([sdk,bundled])]){const base=path.join(root,'build-tools');if(!fs.existsSync(base))continue;for(const v of fs.readdirSync(base).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}))){const file=path.join(base,v,'aapt.exe');if(fs.existsSync(file))return file;}}
 throw Error('Les outils APK fournis avec Studio sont absents. Reinstaller le paquet complet de Studio.');
 }
 async function inspect(file){if(path.extname(file).toLowerCase()!=='.apk'||!fs.statSync(file).isFile()||fs.statSync(file).size>2*1024**3)throw new Error('Sélectionner un fichier APK valide de moins de 2 Go.');const info=await run(aapt(),['dump','badging',file]);const pkg=(info.match(/^package: name='([^']+)'/m)||[])[1];if(!pkg||!/^\w+(?:\.\w+)+$/.test(pkg))throw new Error('Identifiant Android invalide.');return {file,package:pkg,minApi:(info.match(/sdkVersion:'(\d+)'/)||[])[1],abis:(info.match(/native-code: (.+)/)||[])[1]||'Sans bibliothèque native déclarée',tv:/LEANBACK_LAUNCHER|leanback-launchable-activity|android.software.leanback/.test(info),requiredFeatures:[...info.matchAll(/^uses-feature: name='([^']+)'/gm)].map(m=>m[1]),activity:(info.match(/launchable-activity: name='([^']+)'/)||[])[1]||'',hash:await new Promise((resolve,reject)=>{const hash=crypto.createHash('sha256'),stream=fs.createReadStream(file);stream.on('data',chunk=>hash.update(chunk));stream.on('error',reject);stream.on('end',()=>resolve(hash.digest('hex')));})};}
 async function selectApk(file){detectSdk();const original=fs.realpathSync(file);if(path.extname(original).toLowerCase()!=='.apk'||!fs.statSync(original).isFile()||fs.statSync(original).size>2*1024**3)throw new Error('Sélectionner un fichier APK valide de moins de 2 Go.');const directory=path.join(app.getPath('userData'),'android-apks');fs.mkdirSync(directory,{recursive:true});const stagedFile=path.join(directory,crypto.randomUUID()+'.apk');await fs.promises.copyFile(original,stagedFile,fs.constants.COPYFILE_EXCL);try{const inspected=await inspect(stagedFile);if(selected?.stagedFile)try{fs.unlinkSync(selected.stagedFile)}catch{}selected={...inspected,file:original,stagedFile};packageName='';return {apk:{...selected,stagedFile:undefined}}}catch(error){try{fs.unlinkSync(stagedFile)}catch{}throw error}}
 on('pick',async()=>{const r=await dialog.showOpenDialog({title:'Sélectionner un APK Android',properties:['openFile'],filters:[{name:'Application Android',extensions:['apk']}]});if(r.canceled)return {canceled:true};return selectApk(r.filePaths[0])});
 on('create',async p=>{if(typeof p.profile!=='string'||!Object.hasOwn(PROFILES,p.profile))throw new Error('Profil invalide');const image=images().find(i=>i.id===p.image);if(!image)throw new Error('Sélectionner une image système installée.');if(p.profile==='tv'&&!/android-tv|google-tv/.test(image.tag))throw new Error('Android TV nécessite une véritable image Android TV / Google TV, pas une image téléphone.');if(p.profile!=='tv'&&/android-tv|google-tv/.test(image.tag))throw new Error('Cette image est réservée à Android TV.');const name='AIS_'+p.profile+'_'+crypto.randomUUID().replace(/-/g,''),dir=avdHome(),folder=path.join(dir,name+'.avd'),profile=p.nativeSimulator&&p.profile==='tv'?{width:3840,height:2160,density:320}:PROFILES[p.profile];fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(folder);const imageDir=path.join(sdk,'system-images',...image.id.split('/'));
 fs.writeFileSync(path.join(folder,'config.ini'),Object.entries({'AvdId':name,'avd.ini.displayname':name,'image.sysdir.1':imageDir+path.sep,'abi.type':image.abi,'hw.cpu.arch':image.abi==='x86_64'?'x86_64':image.abi,'hw.cpu.ncore':2,'hw.ramSize':2048,'hw.lcd.width':profile.width,'hw.lcd.height':profile.height,'hw.lcd.density':profile.density,'hw.keyboard':'yes','hw.gpu.enabled':'yes','hw.gpu.mode':'auto','hw.mainKeys':p.profile==='tv'?'yes':'no','hw.device.name':p.profile==='tv'?'Android TV':p.profile,'disk.dataPartition.size':'4G','showDeviceFrame':'no','skin.name':profile.width+'x'+profile.height,'tag.id':image.tag,'fastboot.forceColdBoot':'no'}).map(([k,v])=>k+'='+v).join('\n'));fs.writeFileSync(path.join(dir,name+'.ini'),'avd.ini.encoding=UTF-8\npath='+folder+'\ntarget='+image.api+'\n');return {name};});
 on('start',async p=>{
  if(busy)throw Error('Démarrage déjà en cours.');if(!avds().some(a=>a.name===p.name)||!/^[-\w.]+$/.test(p.name))throw Error('Appareil inconnu.');busy=true;
  const context={cancelled:false};pendingStart=context;const session=require('./emulator-session.cjs'),query=(args,timeout)=>run(tool('platform-tools/adb.exe'),args,timeout);
  try{const listing=await adb(['devices']),processes=await session.listProcesses(run);const existing=await session.findRunningAvd({name:p.name,listing,processes,query});
   let recovered=false;if(existing){notify(videoOwner,{stage:'boot',message:'Connexion à l’instance Android existante…'});const ready=await session.resumeExisting({existing,query,cancelled:()=>context.cancelled,terminate:async found=>{notify(videoOwner,{stage:'boot',message:'Instance Android bloquée · redémarrage sans effacer les données…'});await session.terminateManagedAvd({name:p.name,pid:found.pid,sdk,avdHome:avdHome(),run});}});if(ready){serial=existing.serial;return {serial,reused:true};}recovered=true;}
   if(context.cancelled)throw Error('Démarrage Android annulé.');const refreshed=await adb(['devices']);const current=refreshed.match(/emulator-(\d+)\s/g)||[];let port=5554;while(current.some(s=>s.includes('emulator-'+port)))port+=2;if(port>5682)throw Error('Aucun port émulateur disponible.');
   const child=spawn(tool('emulator/emulator.exe'),emulatorStartArgs(p,port),{shell:false,windowsHide:true,env:{...process.env,ANDROID_AVD_HOME:avdHome()},stdio:['ignore','pipe','pipe'],detached:true});let failure='',emulatorLog='';const collect=data=>{emulatorLog=(emulatorLog+cleanEmulatorLog(data.toString())).slice(-12000)};child.stdout.on('data',collect);child.stderr.on('data',collect);child.on('error',e=>failure=e.message);child.on('exit',c=>{if(c!==0){const logPath=path.join(app.getPath('userData'),'android-emulator-last.log');try{fs.writeFileSync(logPath,emulatorLog)}catch{}failure='Le moteur Android s’est arrêté (0x'+(c>>>0).toString(16).toUpperCase()+'). Journal : '+logPath+'\n'+emulatorLog.slice(-1800)}});child.unref();const target='emulator-'+port;launched.add(target);
   try{await session.waitForBoot({target,query,failure:()=>failure,cancelled:()=>context.cancelled});serial=target;return {serial,recovered};}
   catch(error){if(/multiple emulators with the same AVD/i.test(failure)){launched.delete(target);const found=await session.findRunningAvd({name:p.name,listing:await adb(['devices']),processes:await session.listProcesses(run),query});if(found){await session.waitForBoot({target:found.serial,query,cancelled:()=>context.cancelled});serial=found.serial;return {serial,reused:true};}}throw error;}
  }finally{busy=false;if(pendingStart===context)pendingStart=null}
 });
 on('cancel-start',async()=>{if(pendingStart)pendingStart.cancelled=true;return {canceled:!!pendingStart};});
 on('connect',async p=>{await video.stop();serial=String(p.serial);await device();return {serial};});
 mutations.add('update-source');
 on('update-source',async p=>{
  await device();if(serial.startsWith('emulator-'))throw Error('Choisir un téléphone réel pour cette actualisation.');
  const file=resolveApk(p.source,true),info=await inspect(file);
  if(p.source?.apkProject?.package&&info.package!==p.source.apkProject.package)throw Error('Package APK incohérent.');
  await selectApk(file);
  const installed=await operations.get('install')({});
  await adb(['-s',serial,'shell','am','force-stop',info.package]);await launchCurrent();
  return {...installed,updated:true};
 });
 on('install',async()=>{await device();if(!selected)throw new Error('Sélectionner un APK.');const current=await inspect(selected.stagedFile);if(current.hash!==selected.hash)throw new Error('Le fichier APK a changé : le sélectionner à nouveau.');const supported=(await adb(['-s',serial,'shell','getprop','ro.product.cpu.abilist'])).trim().split(',');const native=[...selected.abis.matchAll(/'([^']+)'/g)].map(m=>m[1]);if(native.length&&!native.some(abi=>supported.includes(abi)))throw new Error('Architecture incompatible : APK '+native.join(', ')+' ; appareil '+supported.join(', '));const api=Number((await adb(['-s',serial,'shell','getprop','ro.build.version.sdk'])).trim());if(Number(selected.minApi)>api)throw new Error('API Android '+api+' insuffisante : APK exige '+selected.minApi);const result=await run(tool('platform-tools/adb.exe'),['-s',serial,'install','-r',selected.stagedFile],120000);if(!/Success/.test(result))throw new Error(result);packageName=selected.package;const featureText=await adb(['-s',serial,'shell','pm','list','features']);const missing=selected.requiredFeatures.filter(feature=>!featureText.includes('feature:'+feature));return {message:result+(missing.length?'\nFonctions matérielles à vérifier : '+missing.join(', '):''),package:packageName,warnings:missing};});
 async function launchCurrent(){await device();if(!packageName)throw new Error('Installer l’APK sélectionné avant de lancer.');let component='';for(const category of ['android.intent.category.LEANBACK_LAUNCHER','android.intent.category.LAUNCHER']){const r=await adb(['-s',serial,'shell','cmd','package','resolve-activity','--brief','-a','android.intent.action.MAIN','-c',category,packageName]);component=r.split(/\r?\n/).find(s=>/^[\w.$]+\/[\w.$]+$/.test(s.trim()))?.trim()||'';if(component)break}if(!component)throw new Error('Aucune activité téléphone/TV lançable.');const result=await adb(['-s',serial,'shell','am','start','-W','-n',component]);if(/Error:|Exception/.test(result))throw new Error(result);return {message:result};}
 on('launch',launchCurrent);
 on('installed',async()=>{await device();const output=await adb(['-s',serial,'shell','pm','list','packages','-3']);return {packages:output.split(/\r?\n/).filter(v=>v.startsWith('package:')).map(v=>v.slice(8).trim())}});
 on('launch-installed',async p=>{await device();if(typeof p.package!=='string'||!/^\w+(?:\.\w+)+$/.test(p.package))throw new Error('Package invalide');const list=await adb(['-s',serial,'shell','pm','list','packages','-3']);if(!list.split(/\r?\n/).some(v=>v.trim()==='package:'+p.package))throw new Error('Application absente de cet appareil');packageName=p.package;return await launchCurrent()});
 const keys={up:19,down:20,left:21,right:22,ok:23,back:4,home:3,menu:82,play:85,volumeUp:24,volumeDown:25};
 on('key',async p=>{await device();if(!Object.hasOwn(keys,p.key))throw new Error('Touche invalide');await adb(['-s',serial,'shell','input','keyevent',String(keys[p.key])]);return {};});
 on('pointer',async p=>{await device();const vals=[p.x,p.y,...(p.kind==='swipe'?[p.x2,p.y2]:[])];if(!vals.every(n=>Number.isInteger(n)&&n>=0&&n<=8192)||!['tap','swipe'].includes(p.kind))throw new Error('Coordonnées invalides');await adb(['-s',serial,'shell','input',p.kind,...vals.map(String),...(p.kind==='swipe'?['350']:[])]);return {};});
 on('text',async p=>{await device();if(typeof p.text!=='string'||! /^[a-zA-Z0-9 .,!?@_+-]{1,200}$/.test(p.text))throw new Error('Saisie limitée aux caractères latins simples, chiffres et ponctuation affichée (200 caractères).');await adb(['-s',serial,'shell','input','text',p.text.replace(/ /g,'%s')]);return {};});
 on('frame',async()=>{await device();const data=await run(tool('platform-tools/adb.exe'),['-s',serial,'exec-out','screencap','-p'],15000,true);if(data.length<24||data.readUInt32BE(0)!==0x89504e47)throw new Error('Capture Android invalide');return {url:'data:image/png;base64,'+data.toString('base64'),width:data.readUInt32BE(16),height:data.readUInt32BE(20)};});
 on('capture',async()=>{await device();const r=await dialog.showSaveDialog({defaultPath:'android-'+Date.now()+'.png',filters:[{name:'Capture PNG',extensions:['png']}]});if(r.canceled)return {canceled:true};const data=await run(tool('platform-tools/adb.exe'),['-s',serial,'exec-out','screencap','-p'],15000,true);fs.writeFileSync(r.filePath,data);return {path:r.filePath};});
 on('logs',async()=>{await device();let pid='';if(packageName)try{pid=(await adb(['-s',serial,'shell','pidof',packageName])).trim().split(/\s+/)[0]}catch{}const errors=await adb(['-s',serial,'logcat','-d','-t','250',...(/^\d+$/.test(pid)?['--pid='+pid]:[]),'*:E']);return {message:(/^\d+$/.test(pid)?'Erreurs de '+packageName+' (PID '+pid+') :\n':'Erreurs système / applications :\n')+(errors||'Aucune erreur dans les 250 dernières lignes. Les services Google et le matériel virtuel doivent être vérifiés dans le fonctionnement réel.')};});
 on('video-start',async p=>{await device();if(!['balanced','native'].includes(p.quality))throw new Error('Qualité vidéo invalide');return await video.start(serial,p.quality)});
 on('video-stop',async()=>{await video.stop();return {}});
 on('stop',async()=>{await video.stop();await device();if(!launched.has(serial))throw new Error('Studio ferme uniquement les émulateurs démarrés ici.');await adb(['-s',serial,'emu','kill']);launched.delete(serial);serial='';return {};});
 mutations.add('prepare-install');mutations.add('run-source');mutations.add('resize');mutations.add('import-media');
 on('prepare-plan',async p=>{detectSdk();let apk=null;if(p.source)apk=await inspect(resolveApk(p.source,p.useExport!==false));const tv=apk?.tv??p.tv===true,minApi=Number(apk?.minApi)||26;const compatible=images().some(i=>/android-tv|google-tv/.test(i.tag)===tv&&Number(i.api.replace('android-',''))>=minApi);if(fs.existsSync(path.join(sdk,'emulator','emulator.exe'))&&compatible)return {ready:true,downloadBytes:0};preparedPlan=await require('./android-runtime.cjs').plan({tv,minApi,installedSdk:path.join(app.getPath('userData'),'android-sdk')});return {ready:false,...preparedPlan};});
 on('prepare-install',async(p,event)=>{if(!preparedPlan)throw Error('Vérifier les composants nécessaires avant de les installer.');const baseSdk=app.isPackaged?path.join(process.resourcesPath,'apk-runtime','sdk'):path.join(__dirname,'runtime','sdk');const destination=path.join(app.getPath('userData'),'android-sdk');const plan=preparedPlan;await require('./android-runtime.cjs').install({plan,sdk:destination,baseSdk,acceptedLicenses:p.acceptedLicenses,notify:update=>notify(event.sender,update)});sdk=destination;persist();preparedPlan=null;return {sdk};});
 function bestImage(apk){return images().filter(i=>/android-tv|google-tv/.test(i.tag)===apk.tv&&Number(i.api.replace('android-',''))>=Number(apk.minApi||1)).sort((a,b)=>Number(b.api.replace('android-',''))-Number(a.api.replace('android-','')))[0];}
 async function setGeometry(p){
  await device();if(!serial.startsWith('emulator-'))throw Error('Le changement de format automatique est réservé aux émulateurs.');
  const width=Math.round(Number(p.width)),height=Math.round(Number(p.height)),density=Number(p.density)||(selected?.tv?Math.min(240,Math.floor(1920/Math.max(width,height)*160)):320);
  if(!Number.isInteger(width)||!Number.isInteger(height)||width<240||height<240||width>4096||height>4096||density<72||density>640)throw Error('Dimensions Android invalides (240 à 4096 pixels logiques).');
  const factor=density/160;await adb(['-s',serial,'shell','wm','size',Math.round(width*factor)+'x'+Math.round(height*factor)]);await adb(['-s',serial,'shell','wm','density',String(density)]);
  const sizeReport=await adb(['-s',serial,'shell','wm','size']),densityReport=await adb(['-s',serial,'shell','wm','density']);const size=[...sizeReport.matchAll(/(?:Physical|Override) size: (\d+)x(\d+)/g)].at(-1),dpi=[...densityReport.matchAll(/(?:Physical|Override) density: (\d+)/g)].at(-1);if(!size||!dpi)throw Error('Dimensions réelles Android indisponibles.');
  const physicalWidth=Number(size[1]),physicalHeight=Number(size[2]),actualDensity=Number(dpi[1]),actualLogicalWidth=physicalWidth*160/actualDensity,actualLogicalHeight=physicalHeight*160/actualDensity;
  if(Math.abs(actualLogicalWidth-width)>2||Math.abs(actualLogicalHeight-height)>2)throw Error('Android ne peut pas appliquer ce format sur cet appareil virtuel. Choisir un autre format ou un appareil adapté.');
  return {width,height,density:actualDensity,physicalWidth,physicalHeight,actualLogicalWidth,actualLogicalHeight,sizeReport,densityReport};
 }
 on('resize',async p=>{await video.stop();const geometry=await setGeometry(p);return geometry;});
 on('run-source',async(p,event)=>{
  await video.stop();detectSdk();const result=await selectApk(resolveApk(p.source,p.useExport!==false)),apk=result.apk;const image=bestImage(apk);if(!fs.existsSync(path.join(sdk,'emulator','emulator.exe'))||!image)throw Error('Préparer la simulation Android avant de lancer cette application.');
  try{await run(tool('emulator/emulator.exe'),['-accel-check']);}catch(e){throw Error('La virtualisation Windows doit être activée pour Android. '+e.message);}
  const profile=apk.tv?'tv':p.profile?.kind==='tablet'?'tablet':'phone';const settingsPath=path.join(app.getPath('userData'),'studio-android-devices.json');let saved={};try{saved=JSON.parse(fs.readFileSync(settingsPath,'utf8'));}catch{}const key=apk.package+'|'+image.id+'|'+profile+'|studio-683';
  let name=saved[key];if(!name||!avds().some(a=>a.name===name)){name=(await operations.get('create')({profile,image:image.id,nativeSimulator:true})).name;saved[key]=name;fs.writeFileSync(settingsPath,JSON.stringify(saved));}
  notify(event.sender,{stage:'boot',message:'Démarrage de '+(apk.tv?'Android TV':'Android')+'…'});const started=await operations.get('start')({name,headless:true});
  await setGeometry({width:p.profile?.width|| (apk.tv?1280:412),height:p.profile?.height||(apk.tv?720:915)});
  notify(event.sender,{stage:'install',message:'Installation de l’application…'});const installed=await operations.get('install')({});await launchCurrent();const frame=await operations.get('frame')({});notify(event.sender,{stage:'running',message:'Application exécutée sur Android'});
  return {...started,package:apk.package,tv:apk.tv,frame,warnings:installed.warnings};
 });
 on('hierarchy',async()=>{await device();const file='/sdcard/ais-studio-window-'+crypto.randomUUID()+'.xml';let dumpError;try{await adb(['-s',serial,'shell','uiautomator','dump',file]);}catch(e){dumpError=e;}let xml;try{xml=await adb(['-s',serial,'shell','cat',file]);if(!/<hierarchy[ >]/.test(xml)||!xml.includes('</hierarchy>'))throw Error('Hiérarchie Android incomplète.');}catch(e){throw dumpError||e;}finally{await adb(['-s',serial,'shell','rm','-f',file]).catch(()=>{});}const decode=require('./android-ui.cjs').nodes;return {nodes:decode(xml),package:packageName,fresh:true,dumpCompleted:!dumpError};});
 on('import-media',async(p,event)=>{await device();if(!serial.startsWith('emulator-'))throw Error('L’importation de test est réservée aux émulateurs.');const chosen=await dialog.showOpenDialog({title:'Importer des photos de test dans Android',properties:['openFile','multiSelections'],filters:[{name:'Photos',extensions:['jpg','jpeg','png','webp']}]});if(chosen.canceled)return {canceled:true};if(selected?.tv&&!(await adb(['-s',serial,'shell','pm','path','fr.wokgui.studiophotopicker']).catch(()=>'' )).includes('package:')){const picker=app.isPackaged?path.join(process.resourcesPath,'studio-photo-picker.apk'):path.join(__dirname,'android-picker','studio-photo-picker.apk');notify(event.sender,{stage:'install',message:'Installation du sélecteur de photos Studio : confirmer sur Android si demandé.'});await run(tool('platform-tools/adb.exe'),['-s',serial,'install','-r','-g',picker],120000);}if(chosen.filePaths.length>100)throw Error('Importer au maximum 100 photos à la fois.');await adb(['-s',serial,'shell','mkdir','-p','/sdcard/Pictures/InterfaceStudio']);let count=0;for(const file of chosen.filePaths){if(!/\.(jpg|jpeg|png|webp)$/i.test(file)||fs.statSync(file).size>100*1024**2)throw Error('Photo de test invalide ou supérieure à 100 Mo.');const name=path.basename(file).replace(/[^a-zA-Z0-9_.-]/g,'_'),remote='/sdcard/Pictures/InterfaceStudio/'+name;await adb(['-s',serial,'push',file,remote]);await adb(['-s',serial,'shell','am','broadcast','-a','android.intent.action.MEDIA_SCANNER_SCAN_FILE','-d','file://'+remote]);count++;}return {count};});
 return {stopVideo:owner=>!owner||owner.webContents===videoOwner?video.stop():Promise.resolve(),selectApk:async file=>{if(mutationBusy)throw new Error('Une opération Android est déjà en cours. Attendre sa fin.');mutationBusy=true;try{return await selectApk(file)}finally{mutationBusy=false}}};
}
module.exports={register,run,diagnose,PROFILES,emulatorStartArgs,cleanEmulatorLog};
