const path=require('node:path');
function processDevice(name,processes){
 const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 const avd=new RegExp('(?:^|\\s)-avd\\s+(?:"'+escaped+'"|'+escaped+')(?=\\s|$)');
 for(const p of processes){const cmd=String(p.CommandLine||'');if(!avd.test(cmd))continue;const port=Number(cmd.match(/(?:^|\s)-port\s+(\d+)(?=\s|$)/)?.[1]||5554);if(port>=5554&&port<=5682&&port%2===0)return {serial:'emulator-'+port,pid:p.ProcessId};}return null;
}
async function listProcesses(run){if(process.platform!=='win32')return [];const script=`Get-CimInstance Win32_Process -Filter "Name='emulator.exe' OR Name='qemu-system-x86_64.exe' OR Name='qemu-system-aarch64.exe'" | Select-Object ProcessId,CommandLine | ConvertTo-Json -Compress`;const exe=path.join(process.env.SystemRoot||'C:/Windows','System32/WindowsPowerShell/v1.0/powershell.exe');try{const value=JSON.parse((await run(exe,['-NoProfile','-NonInteractive','-Command',script],5000)).trim()||'[]');return Array.isArray(value)?value:[value];}catch{return [];}}
async function findRunningAvd({name,listing,processes,query}){const process=processDevice(name,processes);if(process)return process;const devices=[...listing.matchAll(/^(emulator-\d+)\s+(?:device|offline)\b/gm)].map(m=>m[1]);const candidates=await Promise.all(devices.map(async serial=>{try{const prop=(await query(['-s',serial,'shell','getprop','ro.boot.qemu.avd_name'],2000)).trim();if(prop===name)return {serial};if(prop)return null;}catch{}try{const found=(await query(['-s',serial,'emu','avd','name'],1500)).split(/\r?\n/)[0].trim();if(found===name)return {serial};}catch{}return null;}));return candidates.find(Boolean)||null;}
async function waitForBoot({target,query,failure=()=>'',timeout=180000,pause=ms=>new Promise(r=>setTimeout(r,ms))}){const end=Date.now()+timeout;while(Date.now()<end){const error=failure();if(error)throw Error(error);try{if((await query(['-s',target,'shell','getprop','sys.boot_completed'],3000)).trim()==='1')return;}catch{}await pause(1500);}throw Error('Android ne répond pas encore après 3 minutes. Fermez sa fenêtre ou relancez Studio pour réessayer. La simulation locale reste disponible.');}
module.exports={processDevice,listProcesses,findRunningAvd,waitForBoot};
