'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {formats,validate}=require('../webapp/studio-formats.js');
function normalize(input){
 if(!input||input.schema!==1||!Array.isArray(input.formats)||!input.formats.length||input.formats.length>16||!input.formats.every(validate)||new Set(input.formats.map(p=>p.id)).size!==input.formats.length)throw Error('Formats du projet invalides.');
 if(!input.formats.some(p=>p.id===input.defaultFormat))throw Error('Le format de départ doit faire partie des formats du projet.');
 return {schema:1,id:typeof input.id==='string'?input.id:crypto.randomUUID(),name:String(input.name||'Mon application').slice(0,80),runtime:'web',defaultFormat:input.defaultFormat,formats:input.formats.map(p=>({id:p.id,name:p.name.slice(0,80),width:p.width,height:p.height,kind:p.kind}))};
}
function read(root){try{const file=path.join(root,'studio-project.json');if(!fs.existsSync(file)||fs.statSync(file).size>1024*1024)return null;return normalize(JSON.parse(fs.readFileSync(file,'utf8')));}catch{return null;}}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function files(project){const p=project.formats.find(p=>p.id===project.defaultFormat),kind=p.kind==='smartphone'?'phone':p.kind;return {
 'studio-project.json':JSON.stringify(project,null,2)+'\n',
 'index.html':'<!doctype html>\n<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="studio-screen" content="'+p.width+'x'+p.height+' '+kind+'"><title>'+escape(project.name)+'</title><link rel="stylesheet" href="app.css"></head><body><header id="app-header"><h1 id="app-title">'+escape(project.name)+'</h1><nav aria-label="Navigation"><button id="home-button" aria-pressed="true">Accueil</button><button id="settings-button" aria-pressed="false">Réglages</button></nav></header><main id="app-content"><section id="home-page"><h2 id="welcome-title">Bienvenue</h2><p id="welcome-text">Votre application s’adapte au téléphone, à la tablette, à l’ordinateur et à la télévision.</p><div id="app-grid"><article id="first-card"><h3>Premier élément</h3><p>Modifiez le contenu et la disposition avec l’Éditeur.</p><button id="primary-action">Compteur : 0</button></article><article id="second-card"><h3>Deuxième élément</h3><p>Testez vos adaptations dans Développer multi-formats.</p></article><article id="third-card"><h3>Troisième élément</h3><p>La même application conserve son comportement sur les différents écrans.</p></article></div></section><section id="settings-page" hidden><h2>Réglages</h2><label>Votre nom <input id="name-field" autocomplete="name"></label><button id="save-name">Enregistrer</button><p id="saved-status" role="status"></p></section></main><script src="app.js"></script></body></html>\n',
 'app.css':':root{color-scheme:light;--accent:#7250ce;--surface:#fff;--text:#242134}*{box-sizing:border-box}html,body{margin:0;min-height:100%;font:16px/1.5 system-ui;background:#f4f1f9;color:var(--text)}body{display:flex;flex-direction:column}header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:20px max(16px,4vw);background:var(--surface);flex-wrap:wrap}h1{font-size:clamp(22px,2.6vw,42px);margin:0}nav{display:flex;gap:8px;flex-wrap:wrap}button,input{font:inherit;max-width:100%;padding:12px 16px;border-radius:10px;border:1px solid #ddd4ed}button{background:var(--surface);color:var(--text);cursor:pointer;min-height:44px}button[aria-pressed=true],#primary-action{background:var(--accent);color:white}button:focus-visible,input:focus-visible{outline:3px solid #d69300;outline-offset:4px}main{width:100%;max-width:1800px;margin:auto;padding:clamp(16px,3vw,60px)}#app-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}article{background:var(--surface);border-radius:16px;padding:24px;min-width:0;overflow-wrap:anywhere}[hidden]{display:none!important}#settings-page{max-width:700px}#settings-page label{display:flex;flex-direction:column;gap:8px;margin-bottom:16px}@media(max-width:599px){header{padding:16px;align-items:flex-start;flex-direction:column}nav{width:100%}nav button{flex:1}#app-grid{grid-template-columns:1fr;gap:12px}article{padding:18px}}@media(min-width:600px) and (max-width:1023px){#app-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(min-width:1600px){body{font-size:24px}button,input{min-height:60px;padding:16px 24px}article{padding:36px}#app-grid{gap:32px}}\n',
 'app.js':"'use strict';\nlet count=Number(localStorage.getItem('studio-starter-count')||0);const action=document.getElementById('primary-action');function render(){action.textContent='Compteur : '+count;}render();action.onclick=()=>{count++;localStorage.setItem('studio-starter-count',String(count));render();};function page(settings){document.getElementById('home-page').hidden=settings;document.getElementById('settings-page').hidden=!settings;document.getElementById('home-button').setAttribute('aria-pressed',String(!settings));document.getElementById('settings-button').setAttribute('aria-pressed',String(settings));}document.getElementById('home-button').onclick=()=>page(false);document.getElementById('settings-button').onclick=()=>page(true);const name=document.getElementById('name-field');name.value=localStorage.getItem('studio-starter-name')||'';document.getElementById('save-name').onclick=()=>{localStorage.setItem('studio-starter-name',name.value);document.getElementById('saved-status').textContent='Enregistré';};document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(e.key==='Escape'){page(false);document.getElementById('home-button').focus();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){const items=[...document.querySelectorAll('button,input')].filter(el=>el.getClientRects().length);const index=items.indexOf(document.activeElement);const delta=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;items[(index+delta+items.length)%items.length]?.focus();e.preventDefault();}});\n",
 'README.md':'# '+project.name+'\n\nApplication HTML/CSS/JavaScript créée dans Interface Studio. Ouvrir ce dossier avec Studio. Les formats choisis sont enregistrés dans studio-project.json. Modifier la base commune et ses adaptations avec Développer multi-formats. Les fichiers restent directement modifiables.\n'
};}
function register({ipcMain,dialog,getWindow,startLocalTarget}){
 const trusted=event=>event.sender===getWindow()?.webContents&&event.senderFrame===event.sender.mainFrame;
 ipcMain.handle('studio:create-project',async(event,p)=>{if(!trusted(event))return {ok:false,error:'Origine refusée'};try{
  const known=(p?.formats||[]).map(f=>typeof f==='string'?formats.find(x=>x.id===f):f);const project=normalize({schema:1,name:p?.name,formats:known,defaultFormat:p?.defaultFormat});
  const chosen=await dialog.showOpenDialog(getWindow(),{title:'Choisir où créer l’application',properties:['openDirectory','createDirectory']});if(chosen.canceled)return {ok:false,canceled:true};
  const parent=fs.realpathSync(chosen.filePaths[0]);const slug=project.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)||'application';let root=path.join(parent,'Studio-'+slug),i=2;while(fs.existsSync(root))root=path.join(parent,'Studio-'+slug+'-'+i++);fs.mkdirSync(root);
  for(const [name,text]of Object.entries(files(project)))fs.writeFileSync(path.join(root,name),text,{encoding:'utf8',flag:'wx'});
  const url=await startLocalTarget(root,'index.html');return {ok:true,source:{type:'folder',path:root,root,entry:'index.html',url,label:project.name,studioProject:project},path:root};
 }catch(e){return {ok:false,error:e.message}}});
 ipcMain.handle('studio:project-formats',async(event,p)=>{if(!trusted(event))return {ok:false,error:'Origine refusée'};try{const source=p?.source;if(!source||!['folder','html'].includes(source.type)||source.apkProject)throw Error('Les formats éditables sont disponibles pour un projet web local.');const root=fs.realpathSync(source.type==='html'?path.dirname(source.path):source.path);const original=read(root);const project=normalize({...original,...p.project,schema:1});const file=path.join(root,'studio-project.json');if(fs.existsSync(file)&&!original)throw Error('Le fichier studio-project.json existant n’est pas un projet Studio valide.');const next=file+'.tmp-'+crypto.randomUUID();fs.writeFileSync(next,JSON.stringify(project,null,2)+'\n');fs.renameSync(next,file);return {ok:true,project};}catch(e){return {ok:false,error:e.message}}});
}
module.exports={register,read,normalize,files};
